version: '3.5'
services:
  web:
    build:
      context: app
      dockerfile: Dockerfile
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --workers 8
    volumes:
      - ./app/:/app/
    ports:
      - "8000:8000"
    depends_on:
      - mongo
  mongo:
    image: mongo:4.0.10
    ports:
      - "27017:27017"
    volumes:
      - ./db_data:/data/db
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - web